#spring:
#  application:
#    name: z-wealth-knowledge-rag
#  ai:
#    model:
#      chat: ollama
#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        options:
#          model: gemma4
#      embedding:
#        options:
#          model: nomic-embed-text
#    vectorstore:
#      qdrant:
#        host: localhost
#        port: 6334
#        collection-name: wealth-rag
#        initialize-schema: true
#
#server:
#  port: 8081
#



spring:
  application:
    name: z-wealth-knowledge-rag
  profiles:
    active: dev

  ai:
    model:
      chat: ollama

    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: gemma4
      embedding:
        options:
          model: nomic-embed-text
    mcp:
      client:
        enabled: true
        toolcallback:
          enabled: true
        sse:
          connections:
            market-rate-server:
              url: http://localhost:8084

    vectorstore:
      qdrant:
        host: localhost
        port: 6334
        collection-name: wealth-rag
        initialize-schema: true

  ##### start using postgresql vector DB #####
#    vectorstore:
#      pgvector:
#        initialize-schema: true
#        dimensions: 768
#        distance-type: COSINE_DISTANCE
#
#  datasource:
#    url: jdbc:postgresql://localhost:5432/appdb
#    username: appuser
#    password: apppass
#    driver-class-name: org.postgresql.Driver
  ##### end of using postgresql vector DB #####


server:
  port: 8081

# virtual threads
  threads:
    virtual:
      enabled: true

# logging
logging:
  file:
    path: logs
  level:
    org.springframework.ai: DEBUG
    org.springframework.web: INFO
    org.springframework.web.client: DEBUG
    root: INFO

# actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans
  endpoint:
    health:
      show-details: always

# spring doc - swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
#    enabled: false  -- disable on prod
  api-docs:
    path: /v3/api-docs
#    enabled: false  -- disable on prod
#  show-actuator: true


services:
  customer-data:
    base-url: http://localhost:8082
  compliance-review:
    base-url: http://localhost:8083

# sql server setting
#spring:
#  datasource:
#    url: jdbc:sqlserver://localhost:1433;databaseName=master
#    username: sa
#    password: YourStrong!Passw0rd
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

