package com.shawn.wealth.rag.dto.tool;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema(name = "CompareResponse", description = "Response returned by compare tool")
public record CompareResponse(

        @Schema(
                description = "Operation status",
                example = "SUCCESS"
        )
        String status,

        @Schema(
                description = "Comparison result generated by the LLM",
                example = "TFSA provides tax-free growth, while RRSP offers tax-deductible contributions but taxable withdrawals."
        )
        String comparison
) {
}